type RowLike = Record<string, any>;

export function mapPusslaProfileRow(row: RowLike): RowLike {
  const specialty = row.specialty || row.speciality || "";
  return {
    id: "default",
    name: row.name || "",
    specialty,
    speciality: specialty,
    goalsVersion: row.goals_version || "2021",
    btStartDate: row.bt_start_date || "",
    btEndDate: row.bt_end_date || "",
    stStartDate: row.st_start_date || "",
    stEndDate: row.st_end_date || "",
    homeClinic: row.home_clinic || "",
    personalNumber: row.personal_number || "",
    address: row.address || "",
    postalCode: row.postal_code || "",
    city: row.city || "",
    email: row.email || "",
    mobile: row.mobile || "",
    phoneHome: row.phone_home || "",
    phoneWork: row.phone_work || "",
    supervisor: row.supervisor || "",
    supervisorWorkplace: row.supervisor_workplace || "",
    studyDirector: row.study_director || "",
    studyDirectorWorkplace: row.study_director_workplace || "",
    manager: row.manager || "",
    verksamhetschef: row.verksamhetschef || "",
    stTotalMonths: row.st_total_months ?? 66,
    stEndAttendance: row.st_end_attendance ?? 100,
    stEndISO: row.st_end_iso || "",
    medDegreeCountry: row.med_degree_country || "",
    medDegreeDate: row.med_degree_date || "",
    licenseCountry: row.license_country || "",
    licenseDate: row.license_date || "",
    hasForeignLicense: row.has_foreign_license ?? false,
    foreignLicenses: row.foreign_licenses || [],
    hasPriorSpecialist: row.has_prior_specialist ?? false,
    priorSpecialties: row.prior_specialties || [],
    isThirdCountrySpecialist: row.is_third_country_specialist ?? false,
    btMode: row.bt_mode || "fristående",
    locked: row.locked ?? false,
  };
}
