"use client";

import { useDocumentsIoWorkspace } from "@/components/pussla/hooks/useDocumentsIoWorkspace";
import { useDocumentsFoldersAndCertMenu } from "@/components/pussla/hooks/useDocumentsFoldersAndCertMenu";
import { usePusslaAuxWorkspaceActions } from "@/components/pussla/hooks/usePusslaAuxWorkspaceActions";
import { useDocumentsWorkspaceViewModel } from "@/components/pussla/hooks/useDocumentsWorkspaceViewModel";

export function usePusslaDocumentsAndAuxWorkspace(params: any) {
  const { openDocumentsFor, uploadDocumentForTarget, downloadDocument } = useDocumentsIoWorkspace({
    authUserId: params.authUserId,
    getSessionUser: params.getSessionUser,
    setAuthUser: params.setAuthUser,
    resolveUserId: params.resolveUserId,
    setDocumentsLoading: params.setDocumentsLoading,
    listActivityDocumentsForUser: params.listActivityDocumentsForUser,
    activityDocumentColumns: params.activityDocumentColumns,
    setDocuments: params.setDocuments,
    documentsFolderKey: params.documentsFolderKey,
    parseDocumentTargetFromKey: params.parseDocumentTargetFromKey,
    getDocumentTargetKey: params.getDocumentTargetKey,
    setDocumentsUploading: params.setDocumentsUploading,
    uploadToStorage: params.uploadToStorage,
    insertActivityDocumentRow: params.insertActivityDocumentRow,
    setDocumentsFolderKey: params.setDocumentsFolderKey,
    setDocumentsOpen: params.setDocumentsOpen,
    createSignedUrl: params.createSignedUrl,
    documentsOpen: params.documentsOpen,
    setDocumentsSidebarWidth: params.setDocumentsSidebarWidth,
    setDocumentsUploadDragActive: params.setDocumentsUploadDragActive,
    documentsUploadDropzoneRef: params.documentsUploadDropzoneRef,
    alertFn: params.alertFn,
  });

  const { runCertificateForCertMenu } = useDocumentsFoldersAndCertMenu({
    certMenu: params.certMenu,
    profile: params.profile,
    activities: params.activities,
    courses: params.courses,
    displayDatesForActivity: params.displayDatesForActivity,
    getCourseDisplayTitle: params.getCourseDisplayTitle,
    openPreviewForBtGoals: params.openPreviewForBtGoals,
    openPreviewForPlacement: params.openPreviewForPlacement,
    setSta3Placements: params.setSta3Placements,
    setSta3Courses: params.setSta3Courses,
    setSta3ResearchTitle: params.setSta3ResearchTitle,
    setSta3SupervisorName: params.setSta3SupervisorName,
    setSta3SupervisorSpec: params.setSta3SupervisorSpec,
    setSta3SupervisorSite: params.setSta3SupervisorSite,
    setSta3Open: params.setSta3Open,
    setCourseForModal: params.setCourseForModal,
    setCourseModalOpen: params.setCourseModalOpen,
    normalizeGlobalFolderId: params.normalizeGlobalFolderId,
    documentsCustomFolders: params.documentsCustomFolders,
    setDocumentsCustomFolders: params.setDocumentsCustomFolders,
    alertFn: params.alertFn,
  });

  const { persistTimelineToDb, persistIntygGroupModal, searchHits, runSearchHit } = usePusslaAuxWorkspaceActions({
    activities: params.activities,
    courses: params.courses,
    selectedPlacementId: params.selectedPlacementId,
    searchQuery: params.searchQuery,
    authUserId: params.authUserId,
    getSessionUser: params.getSessionUser,
    setAuthUser: params.setAuthUser,
    isValidISO: params.isValidISO,
    computeMondayDates: params.computeMondayDates,
    isLeave: params.isLeave,
    isZeroAttendanceType: params.isZeroAttendanceType,
    setActivities: params.setActivities,
    setCourses: params.setCourses,
    setAchievements: params.setAchievements,
    setDbAchievements: params.setDbAchievements,
    deleteAchievementsByUserAndPlacement: params.deleteAchievementsByUserAndPlacement,
    deleteAchievementsByUserAndCourse: params.deleteAchievementsByUserAndCourse,
    insertAchievementRows: params.insertAchievementRows,
    listAchievementsByUserId: params.listAchievementsByUserId,
    mapAchievementRow: params.mapAchievementRow,
    groupedMembersForDraft: params.groupedMembersForDraft,
    updatePlacementById: params.updatePlacementById,
    getCourseDisplayTitle: params.getCourseDisplayTitle,
    setSearchOpen: params.setSearchOpen,
    setIupOpen: params.setIupOpen,
    setHemklinikOpen: params.setHemklinikOpen,
    openDocumentsFor,
    switchActivity: params.switchActivity,
    alertFn: params.alertFn,
  });

  const {
    documentsFolderOptions,
    visibleDocuments,
    moveDocumentToFolder,
    commitInlineFolderRename,
    selectedFolderMeta,
    uploadDocumentsFromList,
  } = useDocumentsWorkspaceViewModel({
    activities: params.activities,
    courses: params.courses,
    documents: params.documents,
    documentsCustomFolders: params.documentsCustomFolders,
    documentsFolderKey: params.documentsFolderKey,
    editingFolderValue: params.editingFolderValue,
    getCourseDisplayTitle: params.getCourseDisplayTitle,
    parseDocumentTargetFromKey: params.parseDocumentTargetFromKey,
    setDocuments: params.setDocuments,
    setDocumentsCustomFolders: params.setDocumentsCustomFolders,
    setDocumentsFolderKey: params.setDocumentsFolderKey,
    setEditingFolderKey: params.setEditingFolderKey,
    setEditingFolderValue: params.setEditingFolderValue,
    updateDocumentTarget: params.updateDocumentTarget,
    persistRenamedGlobalFolderIds: params.persistRenamedGlobalFolderIds,
    uploadDocumentForTarget,
    alertFn: params.alertFn,
  });

  return {
    openDocumentsFor,
    uploadDocumentForTarget,
    downloadDocument,
    runCertificateForCertMenu,
    persistTimelineToDb,
    persistIntygGroupModal,
    searchHits,
    runSearchHit,
    documentsFolderOptions,
    visibleDocuments,
    moveDocumentToFolder,
    commitInlineFolderRename,
    selectedFolderMeta,
    uploadDocumentsFromList,
  };
}
