"use client";

import { useRef } from "react";
import { useAgentSnapshotActions } from "@/components/pussla/hooks/useAgentSnapshotActions";
import { useAgentCollectionActions } from "@/components/pussla/hooks/useAgentCollectionActions";
import { useAgentRuntimeActions } from "@/components/pussla/hooks/useAgentRuntimeActions";
import { useAgentAdapterExecutionSummary } from "@/components/pussla/hooks/useAgentAdapterExecutionSummary";

export function usePusslaAgentWorkspace(params: any) {
  const { captureAgentUiSnapshot, restoreAgentUiSnapshot, saveVersionSnapshotBeforeMutation } =
    useAgentSnapshotActions({
      activities: params.activities,
      courses: params.courses,
      selectedPlacementId: params.selectedPlacementId,
      selectedCourseId: params.selectedCourseId,
      selectedPlacementIdRef: params.selectedPlacementIdRef,
      selectedCourseIdRef: params.selectedCourseIdRef,
      activeLane: params.activeLane,
      iupOpen: params.iupOpen,
      iupInitialTab: params.iupInitialTab,
      hemklinikOpen: params.hemklinikOpen,
      scanOpen: params.scanOpen,
      btModalOpen: params.btModalOpen,
      prepareOpen: params.prepareOpen,
      milestoneOverviewOpen: params.milestoneOverviewOpen,
      courseModalOpen: params.courseModalOpen,
      sta3Open: params.sta3Open,
      previewOpen: params.previewOpen,
      profileOpen: params.profileOpen,
      aboutOpen: params.aboutOpen,
      reportOpen: params.reportOpen,
      settingsOpen: params.settingsOpen,
      supervisionSessions: params.supervisionSessions,
      assessmentSessions: params.assessmentSessions,
      directorMeetingSessions: params.directorMeetingSessions,
      specialistCollegiumSessions: params.specialistCollegiumSessions,
      profile: params.profile,
      btEndISO: params.btEndISO,
      dirty: params.dirty,
      setActivities: params.setActivities,
      setCourses: params.setCourses,
      setSelectedPlacementId: params.setSelectedPlacementId,
      setSelectedCourseId: params.setSelectedCourseId,
      setActiveLane: params.setActiveLane,
      setIupOpen: params.setIupOpen,
      setIupInitialTab: params.setIupInitialTab,
      setHemklinikOpen: params.setHemklinikOpen,
      setScanOpen: params.setScanOpen,
      setBtModalOpen: params.setBtModalOpen,
      setPrepareOpen: params.setPrepareOpen,
      setMilestoneOverviewOpen: params.setMilestoneOverviewOpen,
      setCourseModalOpen: params.setCourseModalOpen,
      setSta3Open: params.setSta3Open,
      setPreviewOpen: params.setPreviewOpen,
      setProfileOpen: params.setProfileOpen,
      setAboutOpen: params.setAboutOpen,
      setReportOpen: params.setReportOpen,
      setSettingsOpen: params.setSettingsOpen,
      setSupervisionSessions: params.setSupervisionSessions,
      setAssessmentSessions: params.setAssessmentSessions,
      setDirectorMeetingSessions: params.setDirectorMeetingSessions,
      setSpecialistCollegiumSessions: params.setSpecialistCollegiumSessions,
      setDirty: params.setDirty,
      setPendingSwitchPlacementId: params.setPendingSwitchPlacementId,
      setPendingSwitchCourseId: params.setPendingSwitchCourseId,
      getSessionUser: params.getSessionUser,
      insertTimelineVersionRow: params.insertTimelineVersionRow,
    });

  const lastAgentEffectRef = useRef<{
    atISO: string;
    ok: boolean;
    message: string;
    before: any;
    after: any;
  } | null>(null);
  const agentUndoStackRef = useRef<any[]>([]);

  const {
    listTimelineEntitiesForAgent,
    listInternalGapsForAgent,
    verifyLastActionEffectForAgent,
    previewActionDiffForAgent,
    selectCollectionForAgent,
    applyOperatorToCollectionForAgent,
  } = useAgentCollectionActions({
    activities: params.activities,
    courses: params.courses,
    getPlacementStartISOForAgent: params.getPlacementStartISOForAgent,
    getPlacementEndISOForAgent: params.getPlacementEndISOForAgent,
    setActivities: params.setActivities,
    setCourses: params.setCourses,
    setDirty: params.setDirty,
    lastAgentEffectRef: lastAgentEffectRef as any,
    authUserId: params.authUserId,
    getSessionUser: params.getSessionUser,
    supabase: params.supabase,
    refreshLists: params.refreshLists,
    logAudit: params.logAudit,
  });

  const {
    getActiveContextForAgent,
    clearIupFollowupsForAgent,
    addIupFollowupForAgent,
    addIupSupervisionMeetingsForAgent,
    shiftIupSupervisionMeetingsForAgent,
    removeIupSupervisionMeetingsByDatesForAgent,
    undoLastAgentMutationForAgent,
    openAgentWindow,
    closeAgentWindow,
  } = useAgentRuntimeActions({
    modalFlags: {
      iupOpen: params.iupOpen,
      hemklinikOpen: params.hemklinikOpen,
      scanOpen: params.scanOpen,
      prepareOpen: params.prepareOpen,
      btModalOpen: params.btModalOpen,
      profileOpen: params.profileOpen,
      aboutOpen: params.aboutOpen,
      reportOpen: params.reportOpen,
      settingsOpen: params.settingsOpen,
      sta3Open: params.sta3Open,
      courseModalOpen: params.courseModalOpen,
      previewOpen: params.previewOpen,
      milestoneOverviewOpen: params.milestoneOverviewOpen,
    },
    selectedPlacement: params.selectedPlacement,
    selectedCourse: params.selectedCourse,
    getPlacementStartISOForAgent: params.getPlacementStartISOForAgent,
    getPlacementEndISOForAgent: params.getPlacementEndISOForAgent,
    activeLane: params.activeLane,
    activitiesCount: params.activities.length,
    coursesCount: params.courses.length,
    dirty: params.dirty,
    supabase: params.supabase,
    IUP_SETTINGS_COLUMNS: params.IUP_SETTINGS_COLUMNS,
    normalizeIupSettings: params.normalizeIupSettings,
    upsertIupSettingsOnUserId: params.upsertIupSettingsOnUserId,
    buildIupSettingsUpsertPayload: params.buildIupSettingsUpsertPayload,
    setSupervisionSessions: params.setSupervisionSessions,
    setAssessmentSessions: params.setAssessmentSessions,
    setDirty: params.setDirty,
    inferPhaseFromDateForAgent: params.inferPhaseFromDateForAgent,
    uid: params.uid,
    agentUndoStackRef: agentUndoStackRef as any,
    restoreAgentUiSnapshot: restoreAgentUiSnapshot as any,
    setIupOpen: params.setIupOpen,
    setHemklinikOpen: params.setHemklinikOpen,
    setScanOpen: params.setScanOpen,
    setBtModalOpen: params.setBtModalOpen,
    setPrepareOpen: params.setPrepareOpen,
    setProfileOpen: params.setProfileOpen,
    setAboutOpen: params.setAboutOpen,
    setReportOpen: params.setReportOpen,
    setSettingsOpen: params.setSettingsOpen,
    setSta3Open: params.setSta3Open,
    setCourseModalOpen: params.setCourseModalOpen,
    setPreviewOpen: params.setPreviewOpen,
    setMilestoneOverviewOpen: params.setMilestoneOverviewOpen,
  });

  const { executeAgentAction, getAgentContextSummary } = useAgentAdapterExecutionSummary({
    adapterDeps: {
      setActiveLane: params.setActiveLane,
      openAgentWindow,
      closeAgentWindow,
      setIupInitialTab: params.setIupInitialTab,
      setIupOpen: params.setIupOpen,
      createPlacementFromDateRange: params.createPlacementFromDateRange,
      createCourseFromDateRange: params.createCourseFromDateRange,
      selectPlacementForAgent: params.selectPlacementForAgent,
      selectCourseForAgent: params.selectCourseForAgent,
      updateSelectedPlacementForAgent: params.updateSelectedPlacementForAgent,
      updateSelectedCourseForAgent: params.updateSelectedCourseForAgent,
      selectedPlacement: params.selectedPlacement,
      selectedCourseIdRef: params.selectedCourseIdRef,
      selectedCourseId: params.selectedCourseId,
      courses: params.courses,
      savePlacementToDb: params.savePlacementToDb,
      saveCourseToDb: params.saveCourseToDb,
      setAllProfilePhoneNumbersForAgent: params.setAllProfilePhoneNumbersForAgent,
      extendLastPlacementForAgent: params.extendLastPlacementForAgent,
      shiftPlacementFromEndForAgent: params.shiftPlacementFromEndForAgent,
      transformAllPlacementsDurationForAgent: params.transformAllPlacementsDurationForAgent,
      shiftAllCoursesForAgent: params.shiftAllCoursesForAgent,
      rebalanceCoursesPerHalfYearForAgent: params.rebalanceCoursesPerHalfYearForAgent,
      planTimelineDistributionForAgent: params.planTimelineDistributionForAgent,
      deleteSelectedPlacementForAgent: params.deleteSelectedPlacementForAgent,
      deleteSelectedCourseForAgent: params.deleteSelectedCourseForAgent,
      deletePlacementByMonthYearForAgent: params.deletePlacementByMonthYearForAgent,
      deleteCourseByMonthYearForAgent: params.deleteCourseByMonthYearForAgent,
      convertCourseToUtbildningsmomentForAgent: params.convertCourseToUtbildningsmomentForAgent,
      planStFromSrTemplatesForAgent: params.planStFromSrTemplatesForAgent,
      planCoursesCoverCourseMilestonesForAgent: params.planCoursesCoverCourseMilestonesForAgent,
      syncCoursesMilestonesForAgent: params.syncCoursesMilestonesForAgent,
      summarizeGoalCatalogForAgent: params.summarizeGoalCatalogForAgent,
      summarizeAppSectionsForAgent: params.summarizeAppSectionsForAgent,
      summarizeRoleViewsForAgent: params.summarizeRoleViewsForAgent,
      getActiveContextForAgent,
      listTimelineEntitiesForAgent,
      listInternalGapsForAgent,
      verifyLastActionEffectForAgent,
      previewActionDiffForAgent,
      selectCollectionForAgent,
      applyOperatorToCollectionForAgent,
      clearIupFollowupsForAgent,
      addIupFollowupForAgent,
      addIupSupervisionMeetingsForAgent,
      shiftIupSupervisionMeetingsForAgent,
      removeIupSupervisionMeetingsByDatesForAgent,
      undoLastAgentMutationForAgent,
      colleaguePlacementDescriptions: params.colleaguePlacementDescriptions,
      colleagueCourseDescriptions: params.colleagueCourseDescriptions,
      saveVersionSnapshotBeforeMutation,
    },
    captureAgentUiSnapshot,
    agentUndoStackRef: agentUndoStackRef as any,
    lastAgentEffectRef: lastAgentEffectRef as any,
    summaryDeps: {
      startYear: params.startYear,
      activities: params.activities,
      courses: params.courses,
      getPlacementStartISOForAgent: params.getPlacementStartISOForAgent,
      getPlacementEndISOForAgent: params.getPlacementEndISOForAgent,
      colleaguePlacementDescriptions: params.colleaguePlacementDescriptions,
      colleagueCourseDescriptions: params.colleagueCourseDescriptions,
      srPlacementTemplates: params.srPlacementTemplates,
      srCourseTemplates: params.srCourseTemplates,
      srUtbildningsmomentTemplates: params.srUtbildningsmomentTemplates,
      activeLane: params.activeLane,
      selectedPlacement: params.selectedPlacement,
      selectedCourse: params.selectedCourse,
      modalFlags: {
        iupOpen: params.iupOpen,
        hemklinikOpen: params.hemklinikOpen,
        scanOpen: params.scanOpen,
        prepareOpen: params.prepareOpen,
        btModalOpen: params.btModalOpen,
        profileOpen: params.profileOpen,
        aboutOpen: params.aboutOpen,
        reportOpen: params.reportOpen,
        settingsOpen: params.settingsOpen,
        sta3Open: params.sta3Open,
        courseModalOpen: params.courseModalOpen,
        previewOpen: params.previewOpen,
        milestoneOverviewOpen: params.milestoneOverviewOpen,
      },
      profileGoalsVersion: String((params.profile as any)?.goalsVersion || "okänd"),
      stStartISO: params.stStartISO,
      stEndISO: params.stEndISO,
      goalsCatalog: params.goalsCatalog,
      specialty: (params.profile as any)?.specialty || (params.profile as any)?.speciality || null,
      usesMetisCourses: params.usesMetisCourses,
      redactContactInfoText: params.redactContactInfoText,
    },
  });

  return {
    executeAgentAction,
    getAgentContextSummary,
    captureAgentUiSnapshot,
    restoreAgentUiSnapshot,
  };
}
