"use client";

import { useRef } from "react";
import { useBtStBoundaryWarnings } from "@/components/pussla/hooks/useBtStBoundaryWarnings";
import { useTimelineHydrationLoad } from "@/components/pussla/hooks/useTimelineHydrationLoad";
import { useSelectionBaselineDirty } from "@/components/pussla/hooks/useSelectionBaselineDirty";
import { useSelectionSaveActions } from "@/components/pussla/hooks/useSelectionSaveActions";
import { useTimelineDraftActions } from "@/components/pussla/hooks/useTimelineDraftActions";
import { useDebouncedAutosave } from "@/lib/hooks/useDebouncedAutosave";

export function usePusslaTimelineCoreOrchestration(params: any) {
  useBtStBoundaryWarnings({
    activities: params.activities,
    courses: params.courses,
    profile: params.profile,
    stStartISO: params.stStartISO,
    startYear: params.startYear,
    computeEducationalGaps: params.computeEducationalGaps,
    normalizeGoalsVersion: params.normalizeGoalsVersion,
    isoToDateSafe: params.isoToDateSafe,
    dateToISO: params.dateToISO,
    addMonths: params.addMonths,
    slotToYearMonthHalf: params.slotToYearMonthHalf,
    mondayNearestTo: params.mondayNearestTo,
    sundayNearestTo: params.sundayNearestTo,
    setDismissedGaps: params.setDismissedGaps,
    setBtstWarnActIds: params.setBtstWarnActIds,
    setBtstWarnCourseIds: params.setBtstWarnCourseIds,
  });

  const hydratedRef = useRef(false);
  const pendingScanSelectionRef = useRef<{ kind: "placement" | "course"; dbId: string | number } | null>(null);
  const loadingRef = useRef(false);

  useTimelineHydrationLoad({
    startYear: params.startYear,
    profileRefreshTick: params.profileRefreshTick,
    profile: params.profile,
    stStartISO: params.stStartISO,
    totalYearsNeeded: params.totalYearsNeeded,
    authUserId: params.authUserId,
    loadingRef: loadingRef as any,
    hydratedRef: hydratedRef as any,
    pendingScanSelectionRef: pendingScanSelectionRef as any,
    isValidISO: params.isValidISO,
    getSessionUser: params.getSessionUser,
    fetchProfileById: params.fetchProfileById,
    mapPusslaProfileRow: params.mapPusslaProfileRow,
    ensureProfile: params.ensureProfile,
    normalizeISODateOnlyGlobal: params.normalizeISODateOnlyGlobal,
    setProfile: params.setProfile,
    setStStartISO: params.setStStartISO,
    setStEndISO: params.setStEndISO,
    resolveUserId: params.resolveUserId,
    setAuthUser: params.setAuthUser,
    fetchLockedTimelineRows: params.fetchLockedTimelineRows,
    computeEffectiveStartYear: params.computeEffectiveStartYear,
    setStartYear: params.setStartYear,
    mapLockedPlacementsToActivities: params.mapLockedPlacementsToActivities,
    mapLockedCoursesToTimeline: params.mapLockedCoursesToTimeline,
    phaseForCourseDates: params.phaseForCourseDates,
    dateToISO: params.dateToISO,
    dateToSlot: params.dateToSlot,
    nextHue: params.nextHue,
    inferPlacementPhaseByProfileBt: params.inferPlacementPhaseByProfileBt,
    sanitizeTimelineDrafts: params.sanitizeTimelineDrafts,
    composeHydratedTimelineState: params.composeHydratedTimelineState,
    slotToYearMonthHalf: params.slotToYearMonthHalf,
    mondayNearestTo: params.mondayNearestTo,
    isoToDateSafe: params.isoToDateSafe,
    slotsPerYear: params.slotsPerYear,
    resolvePendingScanSelection: params.resolvePendingScanSelection,
    setSelectedPlacementId: params.setSelectedPlacementId,
    setSelectedCourseId: params.setSelectedCourseId,
    setActiveLane: params.setActiveLane,
    setActivities: params.setActivities,
    setCourses: params.setCourses,
    setYearsAbove: params.setYearsAbove,
    setYearsBelow: params.setYearsBelow,
    setDismissedGaps: params.setDismissedGaps,
  });

  const { baselineRef, restoreBaseline } = useSelectionBaselineDirty({
    selectedPlacementId: params.selectedPlacementId,
    selectedCourseId: params.selectedCourseId,
    selectedPlacement: params.selectedPlacement,
    selectedCourse: params.selectedCourse,
    setDirty: params.setDirty,
    setActivities: params.setActivities,
    setCourses: params.setCourses,
    isPlacementDirty: params.isPlacementDirty,
    isCourseDirty: params.isCourseDirty,
  });

  const { savePlacementToDb, saveCourseToDb, handleAutosave } = useSelectionSaveActions({
    selectedPlacement: params.selectedPlacement,
    selectedCourse: params.selectedCourse,
    activities: params.activities,
    profile: params.profile,
    startYear: params.startYear,
    authUserId: params.authUserId,
    isValidISO: params.isValidISO,
    slotToYearMonthHalf: params.slotToYearMonthHalf,
    dateToISO: params.dateToISO,
    mondayNearestTo: params.mondayNearestTo,
    sundayBeforeAnchor: params.sundayBeforeAnchor,
    isPlacementInBtWindow: params.isPlacementInBtWindow,
    getEffectiveBtWindow: params.getEffectiveBtWindow,
    isoToDateSafe: params.isoToDateSafe,
    addMonths: params.addMonths,
    dateToSlot: params.dateToSlot,
    sanitizeStMilestonesForGoals: params.sanitizeStMilestonesForGoals,
    buildPlacementSupabaseRecord: params.buildPlacementSupabaseRecord,
    buildCourseSupabaseRecord: params.buildCourseSupabaseRecord,
    ensureUserId: params.ensureUserId,
    getSessionUser: params.getSessionUser,
    setAuthUser: params.setAuthUser,
    saveEntityRow: params.saveEntityRow,
    supabase: params.supabase,
    mapPlacementRowForList: params.mapPlacementRowForList,
    mapPlacementRowForDb: params.mapPlacementRowForDb,
    mapCourseRowForList: params.mapCourseRowForList,
    mapCourseRowForDb: params.mapCourseRowForDb,
    upsertById: params.upsertById,
    perfMark: params.perfMark,
    perfMeasure: params.perfMeasure,
    baselineRef: baselineRef as any,
    setDirty: params.setDirty,
    setOverlapWarning: params.setOverlapWarning,
    setActivities: params.setActivities,
    setCourses: params.setCourses,
    setListPlac: params.setListPlac,
    setDbPlacements: params.setDbPlacements,
    setListCourses: params.setListCourses,
    setDbCourses: params.setDbCourses,
    isIsoInBtWindow: params.isIsoInBtWindow,
    logAudit: params.logAudit,
  });

  const {
    addActivityAt,
    updateSelectedPlacement,
    onTypeChange,
    onLabelChange,
    onMonthsChange,
    createCourseAt,
    createPlacementFromDateRange,
    createCourseFromDateRange,
    updateSelectedCourse,
  } = useTimelineDraftActions({
    uid: params.uid,
    activities: params.activities,
    profile: params.profile,
    stStartISO: params.stStartISO,
    startYear: params.startYear,
    slotToYearMonthHalf: params.slotToYearMonthHalf,
    mondayNearestTo: params.mondayNearestTo,
    sundayNearestTo: params.sundayNearestTo,
    dateToISO: params.dateToISO,
    isoToDateSafe: params.isoToDateSafe,
    isValidISO: params.isValidISO,
    addMonths: params.addMonths,
    wouldOverlap: params.wouldOverlap,
    setActivities: params.setActivities,
    setSelectedPlacementId: params.setSelectedPlacementId,
    setSelectedCourseId: params.setSelectedCourseId,
    savePlacementToDb: ((placement: any) => savePlacementToDb(placement)) as any,
    setCourses: params.setCourses,
    switchActivity: ((newPlacementId: string | null, newCourseId: string | null) =>
      params.switchActivity(newPlacementId, newCourseId)) as any,
    saveCourseToDb: ((course: any) => saveCourseToDb(course)) as any,
    dateToSlot: params.dateToSlot,
    computePhaseByEndSlot: params.computePhaseByEndSlot,
    setActiveLane: params.setActiveLane,
    mapMetisGoalsToMilestoneIds: params.mapMetisGoalsToMilestoneIds,
    sanitizeStMilestonesForGoals: params.sanitizeStMilestonesForGoals,
    selectedCourseIdRef: params.selectedCourseIdRef,
    selectedCourseId: params.selectedCourseId,
    btEndISO: params.btEndISO,
    todayISO: params.todayISO,
    normalizeISODateOnlyGlobal: params.normalizeISODateOnlyGlobal,
    setTypeDraft: params.setTypeDraft,
    setLabelDraft: params.setLabelDraft,
    setMonthsDraft: params.setMonthsDraft,
    selectedPlacement: params.selectedPlacement,
    nextHue: params.nextHue,
  });

  useDebouncedAutosave({
    dirty: params.dirty,
    hasSelection: Boolean(params.selectedPlacement || params.selectedCourse),
    delayMs: 1200,
    onAutosave: handleAutosave,
  });

  return {
    baselineRef,
    restoreBaseline,
    savePlacementToDb,
    saveCourseToDb,
    addActivityAt,
    updateSelectedPlacement,
    onTypeChange,
    onLabelChange,
    onMonthsChange,
    createCourseAt,
    createPlacementFromDateRange,
    createCourseFromDateRange,
    updateSelectedCourse,
  };
}
